#.travis.yml

language: node_js
node_js:
  - "6.10"

sudo: required

branches:
  only:
    - master

dist: trusty

cache:
  directories:
    - node_modules

before_script:

script:
  - ng build -prod -aot

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications: 
    slack: lhasau:wnj03GlXRvb8RWLuNBTlreju
    on_success: always